spring:
  datasource:
    url: jdbc:postgresql://peerfect-rds-instance.cdo2amggo1em.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: peerfectadmin
    password: peerfect8848
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    prefix: classpath:/templates/

  config:
    import:
      - optional:application-secret.yml

  mail:
    host: smtp.gmail.com
    port: 587
    username: travelwithme.mail@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

application:
  version: 1.0.0

server:
  port: 8080


